#Mysql
spring:
  datasource:
     url: jdbc:mysql://47.100.174.102:3306/yijian?useUnicode=true&characterEncoding=utf8
     username: test
     password: test
     driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis.mapper-locations: classpath:entity_mapper/*.xml
